export const ADDITIONAL_DEPENDENCIES: { [key: string]: string } = {
    "@radix-ui/react-separator": "^1.0.3",
    "embla-carousel-react": "^8.6.0",
    "@radix-ui/react-tooltip": "^1.0.6",
    "@radix-ui/react-slot": "^1.2.3",
    "@radix-ui/react-toast": "^1.2.14",
    'next-themes': '^0.3.0',
    "@tanstack/react-query": "5.80.2",
    "@dnd-kit/core": "^6.3.1",
    "@dnd-kit/modifiers": "^9.0.0",
    "@dnd-kit/sortable": "^10.0.0",
    "@dnd-kit/utilities": "^3.2.2",
    "@emotion/is-prop-valid": "^1.3.1",
    "@faker-js/faker": "^8.2.0",
    "@hookform/resolvers": "^3.1.0",
    "@radix-ui/react-accessible-icon": "^1.0.3",
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-alert-dialog": "^1.0.4",
    "@radix-ui/react-aspect-ratio": "^1.0.3",
    "@radix-ui/react-avatar": "^1.0.3",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-collapsible": "^1.0.3",
    "@radix-ui/react-context-menu": "^2.1.4",
    "@radix-ui/react-dropdown-menu": "^2.0.5",
    "@radix-ui/react-hover-card": "^1.0.6",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-menubar": "^1.0.3",
    "@radix-ui/react-navigation-menu": "^1.1.3",
    "@radix-ui/react-popover": "^1.0.6",
    "@radix-ui/react-portal": "^1.0.4",
    "@radix-ui/react-progress": "^1.0.3",
    "@radix-ui/react-radio-group": "^1.1.3",
    "@radix-ui/react-scroll-area": "^1.2.3",
    "@radix-ui/react-select": "^2.0.0",
    "@radix-ui/react-slider": "^1.1.2",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/react-tabs": "^1.0.4",
    "@radix-ui/react-toggle": "^1.0.3",
    "@radix-ui/react-toggle-group": "^1.0.4",
};

export const DEV_DEPENDENCIES = {
    "@eslint/js": "^9.25.0",
    "@types/react": "^19.1.2",
    "@types/react-dom": "^19.1.2",
    "@vitejs/plugin-react": "^4.4.1",
    "eslint": "^9.25.0",
    "eslint-plugin-react-hooks": "^5.2.0",
    "eslint-plugin-react-refresh": "^0.4.19",
    "globals": "^16.0.0",
    "typescript": "~5.8.3",
    "typescript-eslint": "^8.30.1",
    "vite": "^6.3.5"
};

export const BASE_DEPENDENCIES: { [key: string]: string } = {
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "motion": "^12.15.0",
    "react-router-dom": "7.2.0",
    'next-themes': '^0.3.0',
    "sonner": "^1.2.3",
    "@permaweb/aoconnect": "0.0.82",
    "clsx": "^2.1.1",
    "tailwind-merge": "^3.2.0",
    "@tanstack/react-query": "5.80.2",
    "class-variance-authority": "^0.7.1",
    "lucide-react": "^0.485.0",
    "@hookform/resolvers": "5.1.1",
    "axios": "1.8.1",
    "@radix-ui/react-dialog": "^1.1.1",
    ...ADDITIONAL_DEPENDENCIES
};