name: Deploy to Contabo VPS (Preview vs Production)

on:
  push:
    branches:
      - master
      - ario

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/github-contabo
          chmod 600 ~/.ssh/github-contabo
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS with tmux
        run: |
          BRANCH="${GITHUB_REF##*/}"

          if [ "$BRANCH" = "master" ]; then
            SESSION="frontend-prod"
            PORT="3001"
          elif [ "$BRANCH" = "ario" ]; then
            SESSION="frontend-prev"
            PORT="3002"
          else
            echo "Branch $BRANCH not configured for deployment."
            exit 1
          fi

          echo "Deploying branch '$BRANCH' to tmux session '$SESSION' on port $PORT..."

          ssh -i ~/.ssh/github-contabo -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} bash -s <<ENDSSH
            set -e
            cd /home/aykansal/tryanon/frontend

            echo "Fetching latest code..."
            git fetch origin "$BRANCH"
            git reset --hard origin/"$BRANCH"

            echo "Installing dependencies..."
            npm install

            echo "Building project..."
            npm run build

            if tmux has-session -t "$SESSION" 2>/dev/null; then
              echo "Restarting existing tmux session: $SESSION"
              tmux send-keys -t "$SESSION" C-c
              sleep 1
              tmux send-keys -t "$SESSION" "PORT=$PORT npm run start" C-m
            else
              echo "Starting new tmux session: $SESSION"
              tmux new-session -d -s "$SESSION" "PORT=$PORT npm run start"
            fi
          ENDSSH
